
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.swing.Action.DEFAULT;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Swapnil
 */
public class Final_submit extends javax.swing.JFrame {

    /**
     * Creates new form Final_submit
     */
       int i;
       String path;
       
    public Final_submit() {
           initComponents();
           hidden.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_image = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        lbl_sec = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        lbl_mob = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_fee_status = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_g2 = new javax.swing.JLabel();
        lbl_g1 = new javax.swing.JLabel();
        lbl_g3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_regist = new javax.swing.JButton();
        lbl_enroll = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lbl_fee = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_paymode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Final Submit");
        setMinimumSize(new java.awt.Dimension(450, 590));
        getContentPane().setLayout(null);

        lbl_image.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_image.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(lbl_image);
        lbl_image.setBounds(300, 20, 110, 110);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Father Name        :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 120, 130, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Course                 :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 150, 130, 30);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Gender                :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 300, 120, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Email ID               :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 270, 130, 30);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Fees Status         :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 330, 120, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Section                :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 180, 130, 30);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Year                     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 210, 130, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Mobile No            :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 240, 130, 30);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Student Name      :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 90, 130, 30);

        lbl_fname.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_fname.setForeground(new java.awt.Color(0, 0, 51));
        lbl_fname.setText("Father Name        :");
        getContentPane().add(lbl_fname);
        lbl_fname.setBounds(200, 120, 200, 30);

        lbl_name.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(0, 0, 51));
        lbl_name.setText("Student Name      :");
        getContentPane().add(lbl_name);
        lbl_name.setBounds(200, 90, 200, 30);

        lbl_course.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(0, 0, 51));
        lbl_course.setText("Course                 :");
        getContentPane().add(lbl_course);
        lbl_course.setBounds(200, 150, 200, 30);

        lbl_sec.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_sec.setForeground(new java.awt.Color(0, 0, 51));
        lbl_sec.setText("Section      :");
        getContentPane().add(lbl_sec);
        lbl_sec.setBounds(200, 180, 200, 30);

        lbl_year.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_year.setForeground(new java.awt.Color(0, 0, 51));
        lbl_year.setText("Year :");
        getContentPane().add(lbl_year);
        lbl_year.setBounds(200, 210, 200, 30);

        lbl_mob.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_mob.setForeground(new java.awt.Color(0, 0, 51));
        lbl_mob.setText("Mobile No  :");
        getContentPane().add(lbl_mob);
        lbl_mob.setBounds(200, 240, 200, 30);

        lbl_email.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 51));
        lbl_email.setText("Email ID    :");
        getContentPane().add(lbl_email);
        lbl_email.setBounds(200, 270, 200, 30);

        lbl_gender.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_gender.setForeground(new java.awt.Color(0, 0, 51));
        lbl_gender.setText("Gender      :");
        getContentPane().add(lbl_gender);
        lbl_gender.setBounds(200, 300, 200, 30);

        lbl_fee_status.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_fee_status.setForeground(new java.awt.Color(0, 0, 51));
        lbl_fee_status.setText("Fees :");
        getContentPane().add(lbl_fee_status);
        lbl_fee_status.setBounds(200, 330, 200, 30);

        jLabel1.setFont(new java.awt.Font("Technical", 0, 36)); // NOI18N
        jLabel1.setText("Portal");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 100, 30);

        jLabel2.setFont(new java.awt.Font("Aristocrat SF", 0, 36)); // NOI18N
        jLabel2.setText("S");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(153, 13, 40, 40);

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Game 2               :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(40, 390, 120, 30);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Game 1               :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 360, 130, 30);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Game 3               :");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 420, 120, 30);

        lbl_g2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_g2.setForeground(new java.awt.Color(0, 0, 51));
        lbl_g2.setText("Game 2               :");
        getContentPane().add(lbl_g2);
        lbl_g2.setBounds(200, 390, 200, 30);

        lbl_g1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_g1.setForeground(new java.awt.Color(0, 0, 51));
        lbl_g1.setText("Game 1               :");
        getContentPane().add(lbl_g1);
        lbl_g1.setBounds(200, 360, 200, 30);

        lbl_g3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_g3.setForeground(new java.awt.Color(0, 0, 51));
        lbl_g3.setText("Game 3               :");
        getContentPane().add(lbl_g3);
        lbl_g3.setBounds(200, 420, 200, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 520, 100, 30);

        btn_regist.setBackground(new java.awt.Color(0, 0, 51));
        btn_regist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_regist.setForeground(new java.awt.Color(255, 255, 255));
        btn_regist.setText("Register");
        btn_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regist);
        btn_regist.setBounds(80, 520, 100, 30);

        lbl_enroll.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_enroll.setForeground(new java.awt.Color(0, 0, 51));
        lbl_enroll.setText("Student Name      :");
        getContentPane().add(lbl_enroll);
        lbl_enroll.setBounds(200, 60, 200, 30);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Enrollment           :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 60, 130, 30);

        hidden.setText("jLabel3");
        getContentPane().add(hidden);
        hidden.setBounds(10, 504, 80, 30);

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 51));
        jLabel24.setText("Fees Amount      :");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(40, 450, 120, 30);

        lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(0, 0, 51));
        lbl.setText("Rs.");
        getContentPane().add(lbl);
        lbl.setBounds(250, 450, 50, 30);

        lbl_fee.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_fee.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(lbl_fee);
        lbl_fee.setBounds(200, 450, 40, 30);

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setText("Payment Mode    :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(40, 480, 120, 30);

        lbl_paymode.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_paymode.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(lbl_paymode);
        lbl_paymode.setBounds(200, 480, 100, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Menu_Page().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registActionPerformed
        String enroll=lbl_enroll.getText();
        String name=lbl_name.getText();
        String fname=lbl_fname.getText();
        String mobile=lbl_mob.getText();
        String email=lbl_email.getText();
        String gender=lbl_gender.getText();
        String course=lbl_course.getText();
        String sec=lbl_sec.getText();
        String year=lbl_year.getText();
        String paymode=lbl_paymode.getText();
        path=hidden.getText();
        int flag=0;
        try
        { Class.forName("java.sql.Driver");
         java.sql.Connection conn=(java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sportal","root","");
         java.sql.PreparedStatement stmt =conn.prepareStatement("select * from student_details where enrol_no='"+enroll+"'");
         ResultSet rs=stmt.executeQuery();
         if(rs.next())
           {  flag=1;  }
          else
           { flag=0; }
        }
        catch(Exception e)
           { e.printStackTrace(); }
        
        if(flag==0)
        { 
        try
         { 
          Class.forName("java.sql.Driver");
          Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sportal","root","");
          PreparedStatement pstmt=(PreparedStatement) conn.prepareStatement("insert into student_details values(?,?,?,?,?,?,?,?,?,?,?)");
          pstmt.setString(1,enroll);
          pstmt.setString(2,name);
          pstmt.setString(3,fname);
          pstmt.setString(4,"5f4dcc3b5aa765d61d8327deb882cf99");
          pstmt.setString(5,gender);
          pstmt.setString(6,course);
          pstmt.setString(7,year);
          pstmt.setString(8,sec);
          pstmt.setString(9,mobile);
          pstmt.setString(10,email);
          pstmt.setInt(11,0);
          int j=pstmt.executeUpdate();
          if(j>0)
          {   JOptionPane.showMessageDialog(null,"Successfully Registered."); 
               this.dispose();
               new Main_Page().setVisible(true);
          }
          else
          {  JOptionPane.showMessageDialog(null,"Record Not Saved"); }    
         
         }
        catch(Exception e)
        {System.out.print(e);}
          
        String g1=lbl_g1.getText();
        String g2=lbl_g2.getText();
        String g3=lbl_g3.getText();
        String fee=lbl_fee.getText();
        String fee_status=lbl_fee_status.getText();
        try
         { 
          Class.forName("java.sql.Driver");
          Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sportal","root","");
          PreparedStatement pstmt=(PreparedStatement) conn.prepareStatement("insert into student_games values(?,?,?,?,?,?,?)");
          pstmt.setString(1,enroll);
          pstmt.setString(2,g1);
          pstmt.setString(3,g2);
          pstmt.setString(4,g3);
          pstmt.setString(5,fee);
          pstmt.setString(6,fee_status);
          pstmt.setString(7," ");
          int j=pstmt.executeUpdate();
          if(j>0)
          {  //JOptionPane.showMessageDialog(null,"Successfully Registered."); 
             //System.out.println("Record Saved of Games");
          }
          else 
          {  //JOptionPane.showMessageDialog(null,"Not Registered."); 
             //System.out.println("Record Not Saved of Games"); 
          }  
         
       }
        catch(Exception e)
        { System.out.print(e); 
          e.printStackTrace();
        }
      }
        else
        {  JOptionPane.showMessageDialog(null,"User already Registered.");  }
        
        this.dispose();
        //new Menu_Page().setVisible(true);
                
    }//GEN-LAST:event_btn_registActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final_submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final_submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final_submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final_submit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_submit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_regist;
    public javax.swing.JLabel hidden;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lbl;
    public javax.swing.JLabel lbl_course;
    public javax.swing.JLabel lbl_email;
    public javax.swing.JLabel lbl_enroll;
    public javax.swing.JLabel lbl_fee;
    public javax.swing.JLabel lbl_fee_status;
    public javax.swing.JLabel lbl_fname;
    public javax.swing.JLabel lbl_g1;
    public javax.swing.JLabel lbl_g2;
    public javax.swing.JLabel lbl_g3;
    public javax.swing.JLabel lbl_gender;
    public javax.swing.JLabel lbl_image;
    public javax.swing.JLabel lbl_mob;
    public javax.swing.JLabel lbl_name;
    public javax.swing.JLabel lbl_paymode;
    public javax.swing.JLabel lbl_sec;
    public javax.swing.JLabel lbl_year;
    // End of variables declaration//GEN-END:variables
}
